### ISSUE TITLE
CUDA compiler is not working right.

### ISSUE THREAD

**Issue by DiogoAABranco** [fraimondo/cudaica#8]
Hi!
I cannot install cudaica. 
I tried a lot of solutions and none worked. 
Has you can see in the screenshot I have cuda toolkit already installed and all the other dependencies. 
I'm using Ubuntu  18.04,3 LTS. 
Intel® Core™2 Quad CPU Q8400 @ 2.66GHz × 4 
GeForce GTX 750 Ti 2gb Twinfrozen OC edition

I know the processor is not that great, that why I want to use Cudaica. 
Can you please try to help me ? Thank you! 
![Captura de ecrã de 2020-03-04 23-13-46](https://user-images.githubusercontent.com/55894612/75932260-e59e6d00-5e6e-11ea-8c72-0794b72faa06.png)

**Comment by fraimondo** [comment]
Can you please post the full log and how you run the `configure` script?

**Comment by DiogoAABranco** [comment]
Sorry for the late response. 
1.I did "sudo -s"
2.cd cudaica
3. $ ./configure --with-cuda_arch=50

[config.log](https://github.com/fraimondo/cudaica/files/4304258/config.log)

Thank you!
